### ISSUE TITLE
Alternate pattern for specifying list endpoint arguments via builder pattern

### ISSUE THREAD

**Issue by tmenier** [ordercloud-api/ordercloud-dotnet-sdk#6]
This pattern also makes heavy use of expressions, allowing you to specify things like `searchOn` fields and filters in a strongly typed manner.

For example,

```c#
await Client.Me.ListProductsAsync(opts => opts
    .SearchFor("foo")
    .SearchOn(p => p.Name, p => p.Description)
    .SortBy(p => p.Name)
    .AddFilter(p => p.Active && p.ShipWeight < 100)
    .Page(1)
    .PageSize(100));
```

will send the following GET request:

```
v1/me/products?search=foo&searchOn=Name,Description&sortBy=Name&Active=true&ShipWeight=<100&page=1&pageSize=100
```

**Filter** expressions are powerful but there are a few caveats related to be aware of:

- Only `==`, `<`, `>`, `<=`, `>=`, `!=` are supported.
- `&&` is supported and will add multiple filters as demonstrated above.
- `||` is supported, but only on multiple checks against the **same property**, i.e. `p.ID == "a" || p.ID == "b"` produces `ID=a|2` in the query string; `p.ID == "a" || p.Name == "a"` is not supported. (Consider using `SearchFor`/`SearchOn` for this scenario.)
- The left side of a filter must be a simple property accessor, such as `p.Active` or `p.ShipWeight ` above.
- The right side of a filter cannot reference the filter subject. For example, `p.ShipWeight == p.ShipHeight` is not allowed; `p` cannot appear on the right side of the expression. (The right side _can_ contain variables, math operators, function calls, etc, as long as it can be evaluated to single value at runtime.)

**Additional caveat**: Due to a C# limitation of not being able to mix dynamics and expressions, you can only use expression-based xp filters if you're also using strongly-typed xp, i.e. `Client.Me.ListProductsAsync<MyXpType>(...)`.

**Comment by tmenier** [comment]
Important to note that this is a non-breaking change. It doesn't replace the the existing way to specify list arguments as individual method args, i.e. `ListProductsAsync(search: "foo", searchOn: "Name,Description")`, it just supplements this with new overloads.

**Comment by crhistianramirez** [comment]
@tmenier  how would Dates work? I tried:
```
.AddFilter(u => u.xp.ClosedDoorDate > DateTime.Today.AddMonths(-6))
````
But that yields this:

```
xp.ClosedDoorDate=%3E12%2F13%2F2018%2012%3A00%3A00%20AM 
````

And then I tried stringifying it but the comparison operator didn't love that.

**Comment by tmenier** [comment]
@crhistianramirez Good point, I actually discovered this too and meant to log it but apparently I never did. One problem is there's no "standard" way to stringify a date (although ISO-8601 as a default would be better than what it does now), but more generally I think what's needed is either a more weakly-typed overload of `AddFilter` that just lets you provide a string, or an optional func param where you can still work with expressions but control the stringification of the value.

In the mean time, the work-arounds are to either store your xp dates as numbers, or use filters the old school way:

```c#
var filters = new Dictionary<string, object>
{
    ["xp.ClosedDoorDate"] = "<" + DateTime.Today.AddMonths(-6).ToString(???)
};
```
