### ISSUE TITLE
Add a public constructor to OrderCloudException

### ISSUE THREAD

**Issue by oliverheywood451** [ordercloud-api/ordercloud-dotnet-sdk#63]
My project using this SDK has catch blocks where I do certain logic if certain OrderCloudExceptions are thrown. In my unit tests I would like to be able to create an OrderCloudException object so that I can mock a failure response from OrderCloud. However, OrderCloudException has no public constructor. 

Could we add public constructor to OrderCloudException? Thank you!

**Comment by tmenier** [comment]
Fixed in 0.10.3
