### ISSUE TITLE
Filter serialization issue in v0.10.1

### ISSUE THREAD

**Issue by djsteinmetz** [ordercloud-api/ordercloud-dotnet-sdk#64]
The filters string in v0.10.1 is serializing incorrectly, and causing issues in requests.

The following SDK method was used in two tests, one using SDK v0.10.1 and the other in v0.10.0.
`await _oc.Me.ListProductsAsync<BuyerProduct>(filters: "xp.Facets.apparel=Tees%20%26%20Tanks", sortBy: "Name", accessToken: user.AccessToken);`

In v0.10.0, the above method yields the following request URI (when observed via Fiddler).  This URI is correct, and yields expected results.
`GET /v1/me/products?searchType=AnyTerm&sortBy=Name&page=1&pageSize=20&xp.Facets.apparel=Tees%20%26%20Tanks HTTP/1.1`

In v0.10.1, the above method yields the following URI, which is incorrect and causes unexpected results.
`GET /v1/me/products?searchType=AnyTerm&sortBy=Name&page=1&pageSize=20&xp.Facets.apparel=Tees%2520%2526%2520Tanks HTTP/1.1`

**Comment by tmenier** [comment]
Thanks for logging this. I can only guess the Flurl 3 upgrade is the culprit. I'll look into that soon.

**Comment by tmenier** [comment]
Confirmed https://github.com/tmenier/Flurl/issues/620

**Comment by tmenier** [comment]
Fixed in 0.10.2
