### ISSUE TITLE
How to implement Faceted Product Search

### ISSUE THREAD

**Issue by jineshprakasan** [ordercloud-api/ordercloud-dotnet-sdk#72]
I have list of string field types in Product xp field and I was trying to add Filter on these list type fields with OR condition as below

var searchText = "UserEnteredText";
var searchFields ="Name";
var filters = "**xp.FieldOne = FieldOneValue1|FieldOneValue2 || xp.FieldTwo = FieldTwoValue1|FieldTwoValue2**";

var products = await _oc.Me.ListProductsAsync(filters: filters, page: args.Page, search: searchText, searchOn: searchFields, searchType: SearchType.AnyTerm, sortBy: sortBy);

But it is not returning the expected result.

Is there any other approach which can achieve the above scenario.Any guidance will be much appreciated.

**Comment by tmenier** [comment]
The boolean logic you provided here is not supported by OrderCloud's query syntax. I would recommend adding a "hint" field to your xp and populating it at the time the product is created or updated, something like `xmp.MeetsComplexCondition=true`, then query on that. For a large catalog, this will also perform better than what you are attempting even if it was supported.

**Comment by tmenier** [comment]
> If user select Category Cat1,Cat2 and Industry Ind1, I need to generate **OR** condition

This isn't how facets work typically and it isn't how they work in OrderCloud. Selecting multiple values of the _same_ facet should OR them together, but selections from _different_ facets should be **AND**'d.

Take a typical example:

https://www.newegg.com/LED-TV/SubCategory/ID-798?cm_sp=Cat_TV-Video_1-_-VisNav-_-All-LED-TVs_1

If I select LG and Samsung under Series, and 2K and 4K under Recommended Resolution, I would only see results where: (series = LR or Samsung) **AND** (resolution = 2K or 4K).

To mimic this using your example, you would want this for your filter:

`"xp.FieldOne=FieldOneValue1|FieldOneValue2&xp.FieldTwo=FieldTwoValue1|FieldTwoValue2"`
